### ISSUE TITLE
How did you organised a multi-script python program for ImageJ?

### ISSUE THREAD

**Issue by phisanti** [multi-template-matching/MultiTemplateMatching-Fiji#10]
I understand this question is not really an "issue", but this is the first project that I have seen that managed to use multiple `*.py` scripts for one plugin. Indeed, this is something I would like to do myself but I am still struggling to find the way. I know that if I drop a `*.py` file to the `/jars/Libs `folder, these will be transformed into `$*.class` files so that I can call the functions in there. However, if instead of a file I drop a folder with several files, they become invisible. Finally, I would like to ask how did you manage to organise the installation logic as you said that by "merging" the `Fiji.app` folder with the "MultiTemplateMatching-Fiji" folder places all the scripts in the right place.

**Comment by LauLauThom** [comment]
Hi there,

Just in case, it should be `jars\Lib` without `s` not `Libs`.
Also to use subdirectories within this Lib directory (ie a custom python package), you need to have an `__init__.py` file (double underscore leading and trailing).

In my case the package is `jars/Lib/Template_Matching`, the underscore in the directory name is not necessary.
Then the import is as following in your scripts.
https://github.com/multi-template-matching/MultiTemplateMatching-Fiji/blob/53437bbb4e7129240c7ecf61443f2d6721ed6da6/Fiji.app/scripts/Plugins/Multi-Template-Matching/Template_Matching_Folder.py#L34

The scripts that should be appearing as plugin in the menu must be in subdirectories of script/Plugins. Also for that you can  check the directory architecture.

I updated the installation instructions, see the readme section.

> as you said that by "merging" the `Fiji.app` folder with the "MultiTemplateMatching-Fiji" folder places all the scripts in the right place.

I meant to say "merge the Fiji.app of MTM with the Fiji.app of your Fiji installation".

**Comment by LauLauThom** [comment]
It seems you managed it, so I close this issue
https://forum.image.sc/t/create-a-multi-file-jython-script/58584/6?u=lthomas
