### ISSUE TITLE
Folder mode not working any more

### ISSUE THREAD

**Issue by zcseresn** [multi-template-matching/MultiTemplateMatching-Fiji#8]
Hi,
I've been using your excellent plugin successfully until now. After the new update to 1.53c, the Folder mode doesn't work any more. When I set everything up and run it, it stops immediately, saying that it's done, even though nothing was computed. There is no error message. The Image and ListImage modes are still fine.  I'm using Windows 10. 
Many thanks for any suggestion,

Zoltan

**Comment by LauLauThom** [comment]
Thanks for the feedback and for spoting the issue!
I an just coming back from vacations, but I will have a look latest next week!
In the mean time, you can try to rollback to earlier version of ImageJ (Help > Update ImageJ) to see if that fixes the issue.

**Comment by zcseresn** [comment]
Hi,
many thanks for getting back to me so promptly, especially that you are just coming back from holiday.
I tried the idea of rolling back to 1.52, unfortunately that still doesn't work. I'll try a new download of an archived ImageJ and see if that works. Maybe one of the dependencies that you rely on was changed with the new update? Hopefully you can figure it out. It is an awesome plugin, we will have a citation of it if our paper goes thru to reviewers and then accepted.
Thanks again!

**Comment by zcseresn** [comment]
Just a quick update: I rolled back to 1.52p and this worked. Thanks for the idea!  Looking forward to the new version though 👍

**Comment by LauLauThom** [comment]
I found and fixed the issue 😊
For some reason, the scijava function checking the file format was not accepting file path as string anymore.
It was a quick fix fortunately, you can get the new version of the plugin via the updater. 
Let me know if that works for you too, then we can safely close the issue ;)

**Comment by zcseresn** [comment]
Cool, it works now!  many thanks for fixing this so quickly!!  👍 
Yes, first such issue raising for me :)
